TOC([

["Unit 1		", 6],
["Text A What Is Accounting? 		", 6],
["Text B The World of Accounting		", 9],
["Text C The Work of the Accountant		", 11],
["Grammar Study Passive Voice (Simple)			", 13],
["Unit 2		", 16],
["Text A Job Opportunities and Building Careers in Accounting		", 16],
["Text B Certified Public Accountant		", 20],
["Text C Accountant		", 23],
["Grammar Study Passive Voice (Continuous)		", 24],
["Unit 3		", 26],
["Text A Accounting as an Information System		", 27],
["Text B Accounting Systems		", 30],
["Text C The Accountant as a Communicator		", 33],
["Grammar Study Passive Voice (Perfect)		", 34],
["Unit 4		", 37],
["Text A Users of Accounting Information		", 37],
["Text B Management Accounting		", 42],
["Text C Financial Accounting		", 45],
["Grammar Study Passive Voice (revision)		", 48],
["Unit 5		", 51],
["Text A Accounting Concepts		", 51],
["Text B Accounting Elements and Procedures		", 57],
["Text C Accounting Measurement		", 60],
["Grammar Study The Gerund (as subject)		", 61],
["Unit 6		", 64],
["Text A Business Transactions and Financial Statements		", 65],
["Text B The Accounting Equation		", 69],
["Text C Accounting Communication through Financial Statements		", 71],
["Grammar Study The Gerund (after prepositions)		", 74],
["Unit 7		", 76],
["Text A Bookkeeping		", 77],
["Text B Bookkeeping (Continued)		", 80],
["Text C Functions of Accounts		", 84],
["Grammar Study The Gerund (revision)		", 85],
["Unit 8		", 87],
["Text A Double-entry Bookkeeping		", 88],
["Text B Accounts as Descriptions of Transactions		", 91],
["Text C The Accounting Cycle		", 93],
["Grammar Study Participle Forms		", 94],
["Unit 9		", 97],
["Text A The Types and the Titles of Accounts		", 97],
["Text B	The Balance Sheet, Journals and Ledgers		", 100],
["Text C Recording Transactions in a Journal		", 103],
["Grammar Study Revision		", 104],
["Unit 10		", 106],
["Text A Why Is the Balance Sheet Often Criticised?		", 106],
["Text B Preparing a Trial Balance		", 109],
["Text C The Trial Balance		", 110],
["Grammar Study Revision		", 112],
["Unit 11		", 114],
["Text A Basic Cost Accounting		", 115],
["Text B Classification of Costs		", 119],
["Text C Costs and Expenses		", 121],
["Grammar Study Revision		", 122],
["Unit 12		", 124],
["Text A Accounting Fundamentals		", 125],
["Text B Relations between Financial Statements		", 129],
["Text C Rules for Entering Transactions		", 131],
["Grammar Study Revision		", 132],
["Unit 13		", 134],
["Text A Auditing		", 135],
["Text B Accounting and Auditing Standards		", 138],
["Text C Development of Auditing		", 140],
["Grammar Study Revision		", 142],
["Unit 14		", 144],
["Text A An Auditor’s Report		", 145],
["Text B Types of Auditor’s Opinions		", 148],
["Text C Role of the Auditor		", 150],
["Grammar Study Revision		", 151]

]);
